###
POST http://localhost:8081/user/registration
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "registerDate": "2023-12-31",
  "password": "secret",
  "shelf": [],
  "id": 1
}

###
POST http://localhost:8081/user/login
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "registerDate": "2023-12-31",
  "password": "8888",
  "shelf": [],
  "id": 1
}