###
POST http://localhost:8081/user/registration
Content-Type: application/json

{
  "name": "dasha",
  "registerDate": "11.12.2023",
  "password": "123456"
}

###
POST http://localhost:8081/user/login
Content-Type: application/json

{
  "name": "kisa",
  "password": "123456"
}

###
POST http://localhost:8081/book/addReview/1
Content-Type: application/json

{
  "reviewText": "Я не читала!",
  "rating": 5,
  "reviewDate": "25.11.2023",
  "userId": 3,
  "userName": "dasha"
}

###
POST http://localhost:8081/review/get/1
Content-Type: application/json

{

}
###
POST http://localhost:8081/user/102/book/16
Content-Type: application/json
